### PR TITLE
3 1 2

### PR DESCRIPTION
**Pull request by alicampbell2**

### CODE REVIEW

**Comment by alicampbell2** [comment]
Reminder to check all libraries are called correctly for functions used (e.g. DT for datatable)

**Comment by ANikolova22** [comment]
##  Code review

#### Documentation

- [ ] README file for the indicator - the name of the file must be edited to be README.md so it renders as default at the bottom of the folder's page on the online repository. Currently you have to open the file to see the contents. 
- [x] Example input and output that run successfully locally.
- [x] Section at the bottom of README - "Code edits that may be needed" - I've found solution for that one, see review comments below
  

#### Functionality

- [x] **Installation**: Installation or build of the code succeeds.
- [x] **Guidelines**: New code conforms to the project contribution
  guidelines.  
- [x] **Example data**: Example output generated using the example input matches the given example output. 
- [x] **csv formatting**: The csv output is correct, given general guidance for csvs (e.g. columns are in 
a logical order, values within columns are in the correct order, sentence case is used, correct terms, observation status column is correctly filled in).  
- [x] Generally it runs fine with the test and 2021 (most recent) data, but things break when the input format varies slightly as it did in 2020. So some fixes are necessary in case they change the formatting again next year (see review comments below)
     
#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: #3h

---

### Review comments

- as the old data is not recalculated (spreadsheet contains just 1 year of data), I downloaded the 2020 source to check plots. The variation in column names and rows caused issues, some of which you outlines in the README. There is a function in SDGupdater package that can help with standardising the column names. 
- first change source data headings to lower case, to avoid issues with any variation of that in the future, e.g. 
`names(source_data) <- tolower(names(source_data))`
- then change the names of the columns with the `rename_column` function in SDGupdater package (see explanation in the [common code dictionary](https://officenationalstatistics.sharepoint.com/:x:/r/sites/SusIneqSDG/_layouts/15/Doc.aspx?sourcedoc=%7BF6A995D7-35C8-4AE1-8DA9-090EE15966F0%7D&file=Common%20code%20dictionary.xlsx&action=default&mobileredirect=true) or by typing `?rename_column` in R after you have loaded the package). This will essentially future-proof any slight changes in column names and also if there are any notes attached to the name (as is the case in the 2020 data). You'll have to do it separately for each column name (I think). For example:
```
source_data <- rename_column(source_data, primary = "place of birth", alternate = "birth", new_name = "place of birth")
source_data <- rename_column(source_data, primary = "all ages", new_name = "mothers all ages")
source_data <- rename_column(source_data, primary = "under 20", alternate = "under", new_name = "mothers under 20")
source_data <- rename_column(source_data, primary = "20 to 24", alternate = "24", new_name = "mothers 20 to 24")
```
etc.... 

Note that I haven't put alternative names for all in the function arguments, just because it seemed like for those there is unlikely to be anything much different. If the name is as expected, the function won't do any changes. I didn't complete the renaming for all columns, but hopefully this is enough to demonstrate. It should make sense once you read the function documentation and run the examples, but if not let me know and we can run through it together! 

- then at line 10 you should change "Place of birth" so it's "place of birth" as we have un-capitalised all headings in the step before.

- this sorts the column name issue but currently things can still break at line 19 (`pivot_wider`) when the source data has empty cells in "Number of previous live born children" - this creates duplicated values with NA entries. I think the best place to correct this would be in the `main_data `variable before the `long_format `transformation (so after your current line 13). 
Perhaps identify if there are empty fields and if yes, then populate the empty fields for that column by carrying over the cell name until you hit a different name, then carry over again etc. Hope that makes sense! I can't think immediately of the code solution, so only outlining the idea here. Once this is sorted, it should run smoothly and be more future-proofed (I tested it on the 2020 spreadsheet by manually correcting all these fields before reading the input, and it works fine! So the correction needs to be done from within update_3-1-2.R).  

- code style improvements - just to say that sometimes the comments run too far to the right of the script page, so not very readable. As a rule of thumb everything in the script should be placed to the user doesn't need to scroll horizontally to see the code. So maybe use more line breaks.

Please let me know if any of this is unclear, and well done! :)

**Comment by alicampbell2** [comment]
@ANikolova22 addressed comments, new program works for 2019 and 2020 data as well

**Comment by ANikolova22** [comment]
Great work, @alicampbell2! Works fine with the two inputs (2020 and 2021), I didn't get any errors and QA file looks fine :) I'll approve for merging. It looks like there will be a conflict with the main branch. That's because Michael and I changed something in the update_indicator_main script, but it will not affect anyone's code. Resolving should be straight forward 

I'll see if I can quickly resolve this as part of this merge to main and then maybe give heads up to the rest of the team in case they get the same.
Thanks!

**Review by ANikolova22 — APPROVED** [review]
Approving merging to main after initial review edits

**Pull request merged**
