### PR TITLE
5 6 1

### PR DESCRIPTION
**Pull request by alicampbell2**

### CODE REVIEW

**Review by MichaelGNairn — COMMENTED** [review]
Initial review done. I will do a further review (more looking at the code itself) and attach as well. 
[Michael Nairn - Code review for 5-6-1.docx](https://github.com/ONSdigital/sdg_data_updates/files/10491823/Michael.Nairn.-.Code.review.for.5-6-1.docx)

**Comment by alicampbell2** [comment]
[Code.review.for.5-6-1_Ali_response.docx](https://github.com/ONSdigital/sdg_data_updates/files/10539998/Code.review.for.5-6-1_Ali_response.docx)

**Comment by MichaelGNairn** [comment]
Great work Ali, especially the changes to the checks file plots and discrepancy table. 

Let's have a quick chat about the 0's/missing data (* in source) as I don't quite follow. It is important that any 0 we include is actually 0, and not a missing/suppressed data point. Once this is clarified happy to approve review and move forward.

**Review by MichaelGNairn — APPROVED** [review]
Happy for this to be merged to main. Well done Ali.

**Pull request merged**
