### PR TITLE
6 2 1

### PR DESCRIPTION
**Pull request by MichaelGNairn**

### CODE REVIEW

**Comment by ANikolova22** [comment]
##  6-2-1 code review

#### Documentation
  
- [ ] README file for the indicator: in line 4. "Open update_indicator_main.R (from sdg_data_updates.Rproj) and set indicator as **4-c-1**"... change to **6-2-1**
- [ ] Example input and output that run successfully locally: Test run fails at checks output with message: 
Quitting from lines 201-202 (6-2-1_checks.Rmd) 
Error in print(XXXXXXXXXXXXXXXX_plot) : 
object 'XXXXXXXXXXXXXXXX_plot' not found
  
#### Functionality

- [x] **Installation**: Installation or build of the code succeeds: yes after correcting for the plot error above
Deleting line 200 of the Rmd chunk solves the problem:
 `{r, echo = FALSE, fig.width=10, fig.height = 10}`
`suppressMessages(print(XXXXXXXXXXXXXXXX_plot))`
- [x] **Guidelines**: New code conforms to the project contribution
  guidelines. (BUT correction to Readme needs to be applied as stated above)
- [x] **Example data**: Example output generated using the example input matches the given example output: example output runs fine, but after correcting for the error above
- [ ] **csv formatting**: 
"Unit measure" in csv should be "Units"
"Unit multiplier" column missing (should be populated with Units)
   
### Further review comments  
- line 20 in update_6-2-1 
`data_safe <- source_data_safe %>%`
`mutate(Series = "Safeley managed element")` - "Safeley" typo should be "Safely"? But seems to run fine anyway
- The table of differences in the check file don't seem populated, but spot checks show there are differences in level. The problem seems to come from the creation of the `comparison` table at line 68. The old and new columns never overlap with data for a difference to be calculated (e.g. if one is populated, the other one is marked as NA).
- The plots don't go beyond 2020 and only the old data seems to be plotted - that's because the checks file always reads from example_output folder and this is hard-coded. 
Line 46 `new_data <- read.csv(paste0("Example_Output/", date, "_6-2-1", ".csv"))`, but instead should use the variable for the output folder as set in the config file, so `read.csv(paste0(output_folder,"/", date, "_6-2-1", ".csv"))`.
- Looks like the first two rows of headline plots should actually be a single overlay plot (the first row is the old data, the second row is the new data).
- Maybe check file should also include Service level = Safely managed service for the plot comparison (as that's the key data for the indicator that currently shows on the landing page)


#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: #1h

**Comment by ANikolova22** [comment]
Hi @MichaelGNairn , it's running now and spot checks show the values are correct, so the plots are fine too. 
However, the table of differences is still not working. I artificially introduced a large difference - it gets plotted correctly but the table doesn't pick up anything - same problem as described above. 

I figured it out though! Didn't notice before, but the csv output actually contains as Series each of the disaggregations (a bit like a matrix formatting) instead of just having "Proportion of population using safely managed sanitation services (%)" for the Series column. If you correct for that, then the table is produced as expected. I didn't trace exactly at what point the Series column gets populated, I just corrected it in the `joined_data` variable in the Rmd file before constructing the `comparison` table, as a quick and dirty way of checking the solution.

**Comment by MichaelGNairn** [comment]
Great, will look at. The headline plots not overlaying was because Tom had put " " (a space) instead of "" (a blank). So the old data was a blank, and the new data was a space. Took AGES to find, as such a nothing difference!

**Comment by ANikolova22** [comment]
Ok, cool - you beat me to it, I just edited my comment above to say where the issue comes from - should be an easy fix for the csv

**Comment by MichaelGNairn** [comment]
Series fix done.

**Comment by ANikolova22** [comment]
Right - sorry I keep spotting things one at a time :D I only noticed this because I was going ahead into doing the actual indicator update and I noticed that the number of rows for the new data are way fewer, which doesn't make sense. It looks like some false cross-disaggregations have been created. For example, Facility type is crossed with Service level at Septic tank x Unimproved, whereas they should be independent. Also Open defecation x Improved latrine or other. This reduces the number of rows, but also gives wrong data.

Also, there is now a duplicated line for sourcing compile_tables.R in `update_indicator_main.R`, which causes an error message (but still runs fine).

**Comment by MichaelGNairn** [comment]
Remedied this now. It was to do with a second full_join, but how the cross-disags were created makes no sense to me because there are no cross-disags across the input files.

**Review by ANikolova22 — APPROVED** [review]
All good, ready to be merged

**Pull request merged**
