### PR TITLE
ODA

### PR DESCRIPTION
**Pull request by EmmaWoodONS**
I don't think there is any need to go through all the scripts with a fine toothcomb as they are all very similar - maybe but just go through a few to see if anything jumps out that should be improved.

The main checks I think it needs are:
1) The code returns what is in the example output folder (no editing of anything required)
2) You can follow the instructions to produce data for all the indicators using real data
3) The logic of the config and compile_tables scripts are clear
4) I haven't missed anything you think would be useful from the QA file

### CODE REVIEW

**Review by MichaelGNairn — COMMENTED** [review]
[QA_update_4-b-1.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714823/QA_update_4-b-1.csv)
[QA_update_6-a-1.csv
[Michael Nairn - Code review for ODA.docx](https://github.com/ONSdigital/sdg_data_updates/files/9714832/Michael.Nairn.-.Code.review.for.ODA.docx)
](https://github.com/ONSdigital/sdg_data_updates/files/9714824/QA_update_6-a-1.csv)
[QA_update_7-a-1.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714825/QA_update_7-a-1.csv)
[QA_update_8-a-1.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714826/QA_update_8-a-1.csv)
[QA_update_9-a-1.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714827/QA_update_9-a-1.csv)
[QA_update_17-9-1.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714828/QA_update_17-9-1.csv)
[QA_update_17-19-1.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714829/QA_update_17-19-1.csv)
[QA_update_2-a-2.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714830/QA_update_2-a-2.csv)
[QA_update_3-b-2.csv](https://github.com/ONSdigital/sdg_data_updates/files/9714831/QA_update_3-b-2.csv)

#### Documentation

Any new code includes all the following forms of documentation:
  
- [X] README file for the indicator
- [X] Example input and output that run successfully locally.
  
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [X] **Function Documentation** as docstrings within the function definition.
- [X] **Examples** demonstrating major functionality, which runs successfully locally.

#### Functionality

- [X] **Installation**: Installation or build of the code succeeds.
- [X] *Guidelines**: New code conforms to the project contribution
  guidelines.  
- [ ] **Example data**: Example output generated using the example input matches the given example output. 


Output mismatch in the Country income classification column. All below files have the same issue. See attached QA files:
•	2-a-2
•	3-b-2
•	4-b-1
•	6-a-1
•	7-a-1
•	8-a-1
•	9-a-1
•	17-9-1
•	17-19-1

Output mismatch in the Type_of_study column See attached QA files:
•	4-b-1




- [ ] **csv formatting**: The csv output is correct, given general guidance for csvs (e.g. columns are in 
a logical order, values within columns are in the correct order, sentence case is used, correct terms are 
used (i.e. ar in the data dictionary), observation status column is correctly filled in).  


•	Symbols in csv output files (e.g. £ comes out as Â£).

•	Wide variety in significant figures (after decimal point in particular), with no clear pattern. Could this be standardised within, and between, the csv output files? 


Remove underscores from column headers and add in Observation status column:
•	4-b-1
•	8-a-1


     
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [X] **Automated tests**: Unit tests cover essential functions for a reasonable range
  of inputs and conditions. All tests pass on your local machine.


#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: # 3 hours

---

### Review comments



•	Please add install.packages(“pander”) and library(pander) as two lines at the start of the compile_tables script.

•	I haven’t got a .html QA file in my output folder. Looking at the code I can’t work out why this is. I will investigate further. 



- alternative methods (could it be written more efficiently or with more clarity?)
- code style improvements (could the code be written more clearly?)

**Review by MichaelGNairn — COMMENTED** [review]
Hi Emma, please see above review. It consists of a word document QA, and then multiple excel files. It looks like a lot, but the vast majority of the files have the same issue to fix.

**Comment by EmmaWoodONS** [comment]
@MichaelGNairn Thanks for the review. Weirdly I don't have the same issue as you with the output so can you please check it again to see if it is fixed? It looks like it is reading character strings as factors for you, so maybe we have a different version of something.

I have added a bit of code that will install any required packages if necessary. library(pander) is already in the Rmarkdown file as that is where it is used, but should now be installed in the fix.

**Comment by MichaelGNairn** [comment]
change to as.character instead of is.character worked.

**Comment by EmmaWoodONS** [comment]
I tried various things to get the £ symbol to display correctly, including specifying fileEncoding as UTF-8, or using writexlsx, but no joy. It looks like this is something to do with Excel rather than R. You can get it to read it correctly by opening a blank excel file and using  'From Text/csv' in the Data tab.

**Comment by EmmaWoodONS** [comment]
@MichaelGNairn I think I have now fixed all issues except the £ which I think can't be fixed. Can you please check you are happy with it (and that you do now get an Rmd html output), and recommend a merge. No rush, though - Thanks!

**Comment by MichaelGNairn** [comment]
This ok to wait until next week? Michael

**Comment by EmmaWoodONS** [comment]
> This ok to wait until next week? Michael

yes - absolutely :)

**Review by MichaelGNairn — APPROVED** [review]
All good and working, with exception of the £ sign issue. Will have to be done manually in excel afterwards.

**Pull request merged**
