### PR TITLE
11 1 1 ew

### PR DESCRIPTION
**Pull request by EmmaWoodONS**
To run this one I have had to filter the live data in the QA_11-1-1.Rmd file lines 85 to 91 because there is an error in it. This bit of code will need removing before it goes live.  
  
To get it to run you will need to:  
1. Run the rename_column file - this is in the process of being altered in SDGupdater, so once that is done the file can be removed from this indicator.  
2. hash out `rm(list=ls())` in update_indicator_main (so that rename_column is not removed)   
  
I have added a line to update_indicator_main that controls whether the example_config or config file is run, because it was a pain having to do it in compile_tables - it would be good to have your opinion on this!   
  
@quartm and @MichaelGNairn I've added you both as I am not sure of how much time you have these days @quartm (no worries if you are still super busy!), but can whoever picks it up note that they have so you don't both end up doing it! Thanks :)

### CODE REVIEW

**Comment by MichaelGNairn** [comment]
@quartm I'm picking this up by the way. Michael

**Comment by MichaelGNairn** [comment]
Love the line that runs "example_config" or "config" dependent upon test_run == TRUE or FALSE. The config/example_config always confuses me, and I end up double crossing myself quite commonly!

**Review by MichaelGNairn — CHANGES_REQUESTED** [review]
[Michael Nairn - Code review for 11-1-1.docx](https://github.com/ONSdigital/sdg_data_updates/files/9930852/Michael.Nairn.-.Code.review.for.11-1-1.docx)


Main issue is adding in instructions in ReadMe file to downlaod data sources to the "Input" folder. 

Two very minor (and may not be necessary) formatting issues in the csv file. 

Michael

**Comment by EmmaWoodONS** [comment]
> Love the line that runs "example_config" or "config" dependent upon test_run == TRUE or FALSE. The config/example_config always confuses me, and I end up double crossing myself quite commonly!

I'm going to add this to all the indicators in main and to the template...

**Comment by EmmaWoodONS** [comment]
##  Code review for 11-1-1. Michael Nairn – 03/11/2022


#### Documentation

Any new code includes all the following forms of documentation:
  
- [ ] README file for the indicator

•	Please add instructions, including [link](https://www.gov.uk/government/statistical-data-sets/dwelling-condition-and-safety), on how to access and download the original data sources. Then to add them to the “Input” folder, NOT the Example_Input folder. 
o	DA3202 and DA3203.
•	Please add instruction to save “example_config” as “config”, and ensure “areas_filename” and “households_filename” are correct, based off the above download.
o	"DA3202_Decent_Homes_-_areas.xlsx"
o	"DA3203_Decent_Homes_-_households.xlsx"


- [X] Example input and output that run successfully locally.
  
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [X] **Function Documentation** as docstrings within the function definition.
- [X] **Examples** demonstrating major functionality, which runs successfully locally.

#### Functionality

- [ ] **Installation**: Installation or build of the code succeeds.

o	Ensure that the rename_column function has been added to SDGupdater and merged to main (I have reviewed this and it is ready to be merged). Then remove rename_column.R from 11-1-1. 



- [X] *Guidelines**: New code conforms to the project contribution
  guidelines.  
- [X] **Example data**: Example output generated using the example input matches the given example output. 



- [ ] **csv formatting**: The csv output is correct, given general guidance for csvs (e.g. columns are in a logical order, values within columns are in the correct order, sentence case is used, correct terms are used (i.e. are in the data dictionary), observation status column is correctly filled in).  


•	Column O (Length of residence) should be “to” instead of “-“ (e.g. 1 to 4 years, not 1-4 years). This is how age is normally done on the platform, but may be different protocol for “Length of residence”?

•	“Minimum Standard” should be sentence case (lower case s in standard)? In column D “Decent homes criteria”



     
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [X] **Automated tests**: Unit tests cover essential functions for a reasonable range of inputs and conditions. All tests pass on your local machine.


#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: # 2 hours

---

### Review comments




- alternative methods (could it be written more efficiently or with more clarity?)
- code style improvements (could the code be written more clearly?)

**Comment by EmmaWoodONS** [comment]
Changes made - do you recommend merging @MichaelGNairn ?

**Comment by MichaelGNairn** [comment]
I recommend merging. Michael

**Pull request merged**
