### PR TITLE
5 a 1

### PR DESCRIPTION
**Pull request by MichaelGNairn**
Hi Katie and Emma,

I have automated Indicator 5-a-1. It works well from my local repo, so hopefully does so from the online repo for you. 

Happy reviewing!

Michael

### CODE REVIEW

**Comment by EmmaWoodONS** [comment]
##  Code review

#### Documentation

Any new code includes all the following forms of documentation:
  
- [ ] README file for the indicator *nearly*
- [ ] Example input and output that run successfully locally.
  
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [x] **Function Documentation** as docstrings within the function definition. *NA*
- [x] **Examples** demonstrating major functionality, which runs successfully locally. *NA*

#### Functionality

- [ ] **Installation**: Installation or build of the code succeeds. *not quite* due to toTitleCase and potentially due to the years selection in the nomis link (see comments).  
- [x] *Guidelines**: New code conforms to the project contribution
  guidelines.  *yes but remove some of the more obvious comments from compile_tables*
- [ ] **Example data**: Example output generated using the example input matches the given example output. 
- [ ] **csv formatting**: The csv output is correct, given general guidance for csvs (e.g. columns are in 
a logical order, values within columns are in the correct order, sentence case is used, correct terms are 
used (i.e. are in the data dictionary), observation status column is correctly filled in).  

     
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [x] **Automated tests**: Unit tests cover essential functions for a reasonable range
  of inputs and conditions. All tests pass on your local machine. *NA*


#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: 2 hours

---

### Review comments
  
Functionality:  
- [ ] For the input (the nomis link), I think it would be best to select ALL dates and then filter for the month == 12 ones in the code. Otherwise I think you will run into issues with the current link at certain times of the year.  
- [ ] Use `str_to_title` from stringr rather than `toTitleCase`. OR add tools to the packages list and `library(tools)`. I have used stringr in other indicators so that would prefer that for consistency but happy for you to use either.  
- [ ] unhash rm(list = ls()) in updtae_indicator main as this could cause issues with the run if there are already objects in the environment with the same name as objects in the 5-a-1 script.  
- [ ] Delete `setwd("D:/Coding_repos/sdg_data_updates")` from the update_indicator_main file (this doesn't cause issues for me because I have this folder in my D drive, but will be a bug for some people). I like that you have unhashed `install(SDGupdater)` though, because otherwise people might end up running old versions of it.    
    
README:  
- [ ] rename so it is README.md (so it automatically opens when you open 5-a-1 online)  
- [ ] Delete step 6 (this also needs removing from the templates) 
  
Example input/output:  
- [ ] Example input and output folders missing - even though there isn't example input as such, I wonder if it is worth saving a bit of the download in an 'example_of_nomis_download' folder
so if for some reason it changes we can see how it has changed? I'll leave that totallyup to you though! Not sure it is worth having example_output as there is no stable example input. But
maybe note that is why it is missing in the readme.  
  
csv formatting:  
- [ ] Yorkshire and The Humber is wrongly capitalised - either don't change region to sentence case OR make sure Yorkshire and **T**he Humber.
- [ ] United Kindom should be "" 
- [ ] I think it would make sense to put GB after the countries, though I guess alphabetical is also fine as there are so few of them.  
- [ ] Where 'estimate is less than 500' I think Obs status should be 'Missing value; suppressed' not 'data exist but were not collected'  
- [ ] Obs status 'Estimate and confidence interval not available since the group sample size is zero or disclosive (0-2)' should also be 'Missing value; suppressed'
  
Other:  
- [ ] QA.md needs writing so we can check the numbers
- [ ] It might be worth a few instructions on how to generate the nomis link. Pretty sure these are in a readme somewhere already but can't remember which indicator. Not a deal breaker though.

**Review by EmmaWoodONS — CHANGES_REQUESTED** [review]
##  Code review

#### Documentation

Any new code includes all the following forms of documentation:
  
- [ ] README file for the indicator *nearly*
- [ ] Example input and output that run successfully locally.
  
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [x] **Function Documentation** as docstrings within the function definition. *NA*
- [x] **Examples** demonstrating major functionality, which runs successfully locally. *NA*

#### Functionality

- [ ] **Installation**: Installation or build of the code succeeds. *not quite* due to toTitleCase and potentially due to the years selection in the nomis link (see comments).  
- [x] *Guidelines**: New code conforms to the project contribution
  guidelines.  *yes but remove some of the more obvious comments from compile_tables*
- [ ] **Example data**: Example output generated using the example input matches the given example output. 
- [ ] **csv formatting**: The csv output is correct, given general guidance for csvs (e.g. columns are in 
a logical order, values within columns are in the correct order, sentence case is used, correct terms are 
used (i.e. are in the data dictionary), observation status column is correctly filled in).  

     
If the code includes functions, or is a function/set of functions for SDGupdater:  
- [x] **Automated tests**: Unit tests cover essential functions for a reasonable range
  of inputs and conditions. All tests pass on your local machine. *NA*


#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: 2 hours

---

### Review comments
  
Functionality:  
- [ ] For the input (the nomis link), I think it would be best to select ALL dates and then filter for the month == 12 ones in the code. Otherwise I think you will run into issues with the current link at certain times of the year.  
- [ ] Use `str_to_title` from stringr rather than `toTitleCase`. OR add tools to the packages list and `library(tools)`. I have used stringr in other indicators so that would prefer that for consistency but happy for you to use either.  
- [ ] unhash rm(list = ls()) in updtae_indicator main as this could cause issues with the run if there are already objects in the environment with the same name as objects in the 5-a-1 script.  
- [ ] Delete `setwd("D:/Coding_repos/sdg_data_updates")` from the update_indicator_main file (this doesn't cause issues for me because I have this folder in my D drive, but will be a bug for some people). I like that you have unhashed `install(SDGupdater)` though, because otherwise people might end up running old versions of it.    
    
README:  
- [ ] rename so it is README.md (so it automatically opens when you open 5-a-1 online)  
- [ ] Delete step 6 (this also needs removing from the templates) 
  
Example input/output:  
- [ ] Example input and output folders missing - even though there isn't example input as such, I wonder if it is worth saving a bit of the download in an 'example_of_nomis_download' folder
so if for some reason it changes we can see how it has changed? I'll leave that totallyup to you though! Not sure it is worth having example_output as there is no stable example input. But
maybe note that is why it is missing in the readme.  
  
csv formatting:  
- [ ] Yorkshire and The Humber is wrongly capitalised - either don't change region to sentence case OR make sure Yorkshire and **T**he Humber.
- [ ] United Kindom should be "" 
- [ ] I think it would make sense to put GB after the countries, though I guess alphabetical is also fine as there are so few of them.  
- [ ] Where 'estimate is less than 500' I think Obs status should be 'Missing value; suppressed' not 'data exist but were not collected'  
- [ ] Obs status 'Estimate and confidence interval not available since the group sample size is zero or disclosive (0-2)' should also be 'Missing value; suppressed'
  
Other:  
- [ ] QA.md needs writing so we can check the numbers
- [ ] It might be worth a few instructions on how to generate the nomis link. Pretty sure these are in a readme somewhere already but can't remember which indicator. Not a deal breaker though.

**Comment by MichaelGNairn** [comment]
This isn't as bad as I envisaged! Hopefully respond by COP.

**Comment by MichaelGNairn** [comment]
Added tools to the packages list. Personally, I really like some of the functions in it, so may be useful for future indicators.

**Comment by MichaelGNairn** [comment]
I think I have addressed everything here now, with exception of making the QA.Rmd file. Will comment when I've got htis done.

**Pull request closed without merging**
