### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MichaelGNairn**

### CODE REVIEW

**Comment by MichaelGNairn** [comment]
@HeatherWhiteONS can see changes made under the "Files changed" tab at top of pull request.

**Comment by ANikolova22** [comment]
So running on the test data doesn't work because test data only has two tabs. The older version of the example_config contained the tabs necessary to make the test run. I assume the change was done to reflect more recent data, but not sure this is needed? 

There is already an explanation in the README "You will likely have to add the newest year into tabnames". Maybe it needs to more explicitly state that the `tabname` variable in the configurations must be edited by the user to reflect all the tabs on the Input file(s), and then you can leave the example_config with the original two tabs only, so the test run works. So under bullet 7. Otherwise everything else seems fine and example output and checks get generated as expected.

**Comment by MichaelGNairn** [comment]
Yes, makes sense. I was editing so it was up to date for new release, and didn't think of example data test. 

Should be ok now.

**Comment by ANikolova22** [comment]
Ok, looks good and works fine. I haven't done any other checks as this automation has already been reviewed I believe, just this minor update.

**Review by ANikolova22 — APPROVED** [review]

**Pull request merged**
