### PR TITLE
5 2 1

### PR DESCRIPTION
**Pull request by MichaelGNairn**
5-2-1 automation ready for review. Note, only 2021/22 data and no data for 2020/21 due to no in-person crime survey. 

Not done the QA checks Rmd file. There are nearly 20 disaggregations, so unsure how easily to make all these plots. Any ideas, please shout!

### CODE REVIEW

**Comment by MichaelGNairn** [comment]
@ANikolova22 @uzzelk  hold off on this for a couple of days. I have an idea R.E. the checks file needing to produce plots comparing 20+ disaggregations. Produce the "table of discrepancies" between old and new data first. Then include a couple of examples of time series plots, that can be amended by the reviewer based on any highlighted discrepancies picked out in the table above. 

I'll make this checks file now, and can see what you think. Steven Jones has done very similar for 13-1-1 (over 100 possible time series') and it works well. 

Something we could implement across lots of indicators, where there are too many time series to efficiently code plots for (e.g. > 10)?

**Comment by ANikolova22** [comment]
Hi @MichaelGNairn, is this ready for reviewing now?

**Comment by MichaelGNairn** [comment]
> Hi @MichaelGNairn, is this ready for reviewing now?

Something isn't quite right with the checks file. Will look when fresh tomorrow.

**Comment by ANikolova22** [comment]
Hi Michael,
Before I go further with this one just wanted to check a few things regarding the source and output... I see the output from this differs a bit in terms of series and disaggregations relative to what is live and the input source spreadsheet varies a bit year to year, seems a bit messy (don't even think we have the variables for 20/21 period?). I understand it's because from 2021 the upper age limit was removed. 
Anyways, just wondering if maybe the indicator needs to be updated first to integrate these changes, so this automation slots nicely with current (updated) and future data, if that makes sense? It just seems like there are some discontinuities at present in terms of the sources and layout for the indicator, can't work out the practicalities exactly - will spend some time on this next week.

**Comment by MichaelGNairn** [comment]
Hi Atanaska, very good points. Automating this, while also incorporating the substantial changes to the source, is probably a bit risky? Best to update manually, and then prepare the automation to be used with the next release?

**Comment by MichaelGNairn** [comment]
Paused automation in favour of manual update. This is due to substantial change to data source, a key reason for an indicator being not ideal to automate.

**Comment by MichaelGNairn** [comment]
Paused automation in favour of manual update. This is due to substantial change to data source, a key reason for an indicator being not ideal to automate.

**Pull request closed without merging**
