### PR TITLE
3 9 1

### PR DESCRIPTION
**Pull request by EmmaWoodONS**

### CODE REVIEW

**Review by MichaelGNairn — COMMENTED** [review]
[Michael Nairn Code review for 3-9-1.docx](https://github.com/ONSdigital/sdg_data_updates/files/10426427/Michael.Nairn.Code.review.for.3-9-1.docx)

Please see attached review. Emma, happy to take off you and get someone else to review? However, very little needs doing (beyond getting the checks file to work). 

Cheers, Michael

**Comment by MichaelGNairn** [comment]
I have picked up this off @EmmaWoodONS . 

@ANikolova22 or @uzzelk have requested your review, which I will respond to. No urgency. 

One note: 
I can’t get the Checks file to run, and get the below error:
	“Error in yaml::yaml.load(..., eval.expr = TRUE) :   Scanner error: while scanning for the next token at line 3, column 7 found character that cannot start any token at line 3, column 7”

**Review by MichaelGNairn — APPROVED** [review]

**Review by uzzelk — CHANGES_REQUESTED** [review]
# 3-9-1 automation review

#### Documentation

Any new code includes all the following forms of documentation:
  
- [x] README file for the indicator
- [x] Example input and output that run successfully locally.
  
#### Functionality

- [ ] **Installation**: Installation or build of the code succeeds. 
•	Update_3.9.1.R runs and produces expected output but issues with 3-9-1_checks.Rmd caused the code to fail when run altogether
- [x] *Guidelines**: New code conforms to the project contribution
  guidelines.  
- [x] **Example data**: Example output generated using the example input matches the given example output. 
- [x] **csv formatting**: The csv output is correct, given general guidance for csvs 


#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: # 2.5 hours

---

### Review comments

#### README.md
•	Points 2 & 4 could be elaborated on a little so the person knows what data they are downloading (I know you mention it in point 14 but would be good to have it here). It might help the person running the update to name the files better as they both download with the same name (“indicator-data.csv”)

•	Point 14 would be more helpful if you told the person to navigate to folder 3-9-1 as they will initially likely not be in that folder and so the example_config/config files may not be visible

•	Point 16 – remove the comment “You may need to remove the # from line 66 of compile_tables (rmarkdown::render)” as this should always be unhashed?

•	Typos on line 47 (examaple) and line 49 (everythig)

#### Update_3-9-1.R
Produces csv as expected. Have spot checked some of the values (old and new method) against the downloaded source data and they match.

#### 3-9-1_checks.Rmd
QA file not produced, with the following error in the console:
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
Scanner error: while scanning for the next token at line 3, column 7 found character that cannot start any token at line 3, column 7
This seems to be caused by the special characters (`) in line 3 (date: `r Sys.time`). When I delete this line the QA script runs a bit further, but the checks file is still not produced, as I get another error:
Quitting from lines 19-59 (3-9-1_checks.Rmd) Error in paste0(getwd(), "/", input_folder, "/", filename) : object 'filename' not found
This is because line 50 reads:
- filepath for the input data: **`r paste0(getwd(), "/", input_folder, "/", filename)`**
but the object is named csv_filename in the global environment, so I changed filename to csv_filename and then got the following error:
Quitting from lines 19-59 (3-9-1_checks.Rmd) Error in eval(tryCatch(parse_only(code), error = function(e) { : object 'tab_name' not found
This was caused by lines 51, and 52, which don’t seem to be relevant. So I deleted them and then got the following error:
Quitting from lines 138-175 (3-9-1_checks.Rmd) Error in `filter()`: ! Problem while computing `..1 = ... & (is.na(deprivation_decile) | deprivation_decile == "")`. Caused by error in `mask$eval_all_filter()`: ! object 'county' not found 
I can see line 166 reads: (is.na(county) | county == "") & but county doesn’t exist in the old_data, new_data, live_data, or joined_data…

I hashed this line out and then got the following error:
Quitting from lines 193-202 (3-9-1_checks.Rmd) Error in `select()`: ! Can't subset columns that don't exist. x Column `Year` doesn't exist.
This seems to be caused by line 197 and the capitalised Y in Year (it is ‘year’ in the joined_data dataframe), but this is an issue with lines 196 – 202 more generally as Value is also capitalised in 197 and 199. I’m also not sure why Gas is in line 197 as this is not in the dataframe (I’m guessing it’s leftover from another script).

Anyway, when I change the capitalisations and delete ‘Gas’, I get the following error:
Quitting from lines 193-202 (3-9-1_checks.Rmd) Error in `mutate()`:
! Problem while computing `difference = new - live`. Caused by error in `new - live`:
! non-numeric argument to binary operator
I didn’t quite know what to do to fix this, and given all the other issues, I stopped here, but if this is fixed, then the script should (hopefully) run okay!

**Comment by uzzelk** [comment]
> @uzzelk and @MichaelGNairn, do you want me to have a look at this or would that complicate it at this stage? :D Katie, the code edits/ bug fixes you describe in your latest review message, are they integrated into this branch now?

@ANikolova22 No, I've not changed the code at all on this branch (I created a 3-9-1_review branch on my local repository to do the review as I didn't want to break anything further!)

**Comment by MichaelGNairn** [comment]
@uzzelk amazing review, thanks a lot! 

When I initially reviewed this for Emma I couldn't get the checks file to work, despite trying numerous things, so I'm very grateful for the work through. I'll implement all of your suggestions tomorrow and hopefully a checks file appears!! 

Will update tomorrow

**Comment by MichaelGNairn** [comment]
@uzzelk  getting there! 

CLicking source on updat eindicator main now gets as far as:
"Quitting from lines 191-205 (3-9-1_checks.Rmd) 
Error: Problem with `mutate()` column `difference`.
i `difference = new - live`.
x non-numeric argument to binary operator"

I can't recall having this issue before, and it may be to do with how Emma coded her checks file. Will have a dive later today after a break from checks files!! 

Thanks a lot

**Comment by MichaelGNairn** [comment]
@uzzelk checks file now producing properly. As expected, Emma had done something clever I couldn't work out, so have stripped it back to be similar style to other checks files. 

Hope all running ok now.

**Comment by uzzelk** [comment]
Thanks for making the changes to the README.md, it’s much clearer now in terms of what source link is downloading what data.

Code now runs as a whole, and the csv is produced as expected. Have not re-checked values as these were fine last time, and now changes made to the update script.

**3-9-1 checks file**

Now produces – YAY!

Just a few comments:

- Line 3 – Author is still Emma Wood… not sure if this is wrong, but seeing as you rewrote checks file would it make more sense to be in your name?
- Line 27 – missing full stop.
- Lines 32 – 39 – these seems to be guidance for how to write the checks file, not sure if they’ve been left in by accident. Suggest delete and list specific things that might need to be checked in addition to the QA document (e.g., what is written in quotation marks re provisional values).
- Lines 42 – 46 – again, these seems to be guidance for how to write the checks file so suggest deleting.
- Lines 54 – 64 – I’m not too sure what this is telling me to do… Or where to find the comparison information in the metadata tab.
- Lines 137 – 176 – Unsure why only plots for Region are produced for the QA – I guess because it’s too many to do all the LA’s but maybe a sentence stating that would be helpful (if that is the reason).
- Also, in the QA html file, some of the code shows up under the generated plots, that I am not sure if it is meant to be there/what it is for:
- Line 185 – “The following example is taken from 13-2-2:” Do you mean the following sentence or the following code? I’m guessing sentence, but if so, not sure what the relevance is to 3.9.1…

**Comment by MichaelGNairn** [comment]
Thanks Katie. Think those few final changes have been addressed. Thanks

**Pull request merged**
