### PR TITLE
8 10 1

### PR DESCRIPTION
**Pull request by uzzelk**

### CODE REVIEW

**Review by MichaelGNairn — CHANGES_REQUESTED** [review]
[Michael Nairn Code review for 8-10-1.docx](https://github.com/ONSdigital/sdg_data_updates/files/12335681/Michael.Nairn.Code.review.for.8-10-1.docx)

**Comment by MichaelGNairn** [comment]
@uzzelk changes requested. Drop me a message if doesn't make sense.

**Comment by uzzelk** [comment]
@MichaelGNairn I have made the minimum changes for now, but will look to make use of NOMIS APIs to improve this automation in the future (if the situation allows). Changes I have made are:

## README
- Removed duplicate line in banks by region download instructions.
- Added instructions to download region to Las lookup file.
- Point 2 – specified to open sdg_data_updates from Jemalex and not from local drive.

## compile_tables.R
- Added “lubridate” to line 7 under the list of packages to be installed.
- Added library('lubridate') to list beneath.

## update_8-10-1.R
- **I did not do anything to the ordering of the csv as “blank” (United Kingdom) is already first.**
- Added csv_output$Region[csv_output$Region == "East of England”] <- "East" to bottom of script.
- **I also did not change the region ordering.** I also couldn't think of a simple way to do it... you put in your review that it is not a big issue so have left it for now. Could be something I look to do when improving the code in future.

## 8-10-1_checks.Rmd
- Changed table to clickable table (thanks for the code for this - I actually tried it when initially doing the checks file but it wasn't working, as I didn't seem to have the DT package installed 🤭). I have added DT to list of packages in compile_tables.R and also added library(DT) to top of checks file script.

**Comment by MichaelGNairn** [comment]
Looks great, well done Katie! 

Only issue is I am still getting England first in the csv, instead of "blank" for United Kingdom.

**Review by MichaelGNairn — APPROVED** [review]

**Pull request merged**
