### PR TITLE
14 2 1

### PR DESCRIPTION
**Pull request by abhsheksingh**
Automation of 14-2-1 is complete, It is giving me the expected csv file and QA.html document. Please review it carefully as its my first time and I don't wat to mess anything. There is one confusion, the review form will be completed by me or the reviewer ?

### CODE REVIEW

**Comment by MichaelGNairn** [comment]
Yes, as Atanaska says it's for the reviewer to do. I can do later this week.

**Comment by abhsheksingh** [comment]
> The review form is to be completed by the reviewer, you just need to respond to any comments they may have :)

 Thanks Atanaska

**Comment by abhsheksingh** [comment]
> Yes, as Atanaska says it's for the reviewer to do. I can do later this week.

Thanks Micheal

**Review by MichaelGNairn — CHANGES_REQUESTED** [review]
[Michael Nairn - Code review for 14-2-1.docx](https://github.com/ONSdigital/sdg_data_updates/files/10684503/Michael.Nairn.-.Code.review.for.14-2-1.docx)

@abhsheksingh  please see my code review attached. Excellent work, well done!

**Comment by abhsheksingh** [comment]
Addressed the QA comment

**Review by MichaelGNairn — APPROVED** [review]

**Comment by MichaelGNairn** [comment]
Changes all made and approved. Well done Abhishek, you can click the green "merge pull request" button above.

**Pull request merged**
