### PR TITLE
2 3 1

### PR DESCRIPTION
**Pull request by uzzelk**

### CODE REVIEW

**Review by abhsheksingh — CHANGES_REQUESTED** [review]
##  Code review by Abhishek Singh

#### Documentation


  
- [ ] ReadMe for the indicator

    -	Edit point 1. of the Instructions (See review comments)
 


- [x] example_config file for the indicator


- [ ] compile_tables file for the indicator 
    - Line 26 should call “config.R” as opposed to “2-3-1_config.R (See review comments) 

- [x] Example input and output that run successfully locally. 


  

#### Functionality

- [x] **Installation**: Installation or build of the code succeeds. 
- [x] **Guidelines**: New code conforms to the project contribution guidelines. 
- [x] **Example data**: Example output generated using the example input matches the given example output. 
- [x] **csv formatting**: The csv output is correct, given general guidance for csvs (e.g. columns are in 
a logical order, values within columns are in the correct order, sentence case is used, correct terms are 
used (i.e. ar in the data dictionary), observation status column is correctly filled in).  

     

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: 1.5hr

---

### Review comments




1. ReadMe for the indicator

    - 	Edit point 1. of Instructions to read ***"Download the latest data from: https://www.gov.uk/government/statistics/total-factor-productivity-of-the-agricultural-industry. The data can be found in the file with ODS(openDocument Spreadsheet) file format."***
    - 	Although very clear instructions written. 


2. compile_table file for the indicator (Minor changes)

    - 	Edit line 26 to read **"source("config.R") } else { "**, (***to allign with readme instructions***).

3. update_2_3_1 file
    - ***(optional)*** edit line 22 to read "# select necessary rows and format them"
    - ***(optional)*** I would add a few more comments for better understanding of the code functioning, However, I am able to understand through the code so no need I believe.

**Comment by uzzelk** [comment]
Thank you for your review @abhsheksingh - I have made the changes you suggested (apart from extra comments in update file - as you said it is pretty simple code to understand what is going on). Let me know if there is anything else needed 😄

**Comment by abhsheksingh** [comment]
> Thank you for your review @abhsheksingh - I have made the changes you suggested (apart from extra comments in update file - as you said it is pretty simple code to understand what is going on). Let me know if there is anything else needed 😄

Sure thanks for the changes Katie, it is fine as it was optional 😄. Everything is fine you are ready to go.

**Review by abhsheksingh — APPROVED** [review]
All done thanks

**Pull request merged**
