### PR TITLE
3 5 1

### PR DESCRIPTION
**Pull request by MichaelGNairn**

### CODE REVIEW

**Comment by ANikolova22** [comment]
Hi @MichaelGNairn, I just started this review, so only as far as the README, but I noticed that the mentioned file for Source 3 is actually missing. I've got all the other stuff fine, haven't run the code yet but I assume it will fail without that input from Estimates_of_Alcohol_Dependent_Adults_in_England_for_R, as I can see it's required for the `alcohol_prevalence` in the `example_config`

Maybe it was the case that you have it in a local Input folder, rather than Example_input? If so, it would have been uploaded as part of the push because 'Input' is in the gitignore list

**Comment by MichaelGNairn** [comment]
Hmmm, strange.

It's here.

I'll try and sort properly later.

Michael

**Comment by MichaelGNairn** [comment]
> 

All done except alphabetical ordering.

**Comment by MichaelGNairn** [comment]
"I need to check my understanding of the comment on line 247 - do you mean the sums of LAs for the years where total England data is available are very similar to that England figure, so therefore we can assume the sum of LAs can be used to derive the total England figure for all years and use that across the board (that's what the code appears to do anyway)?"
Correct, this is what has been done.

**Comment by ANikolova22** [comment]
Yes - I was actually going to do this today! :)

**Comment by ANikolova22** [comment]
### 3-5-1 follow-on review:

- README still has ?? markers around Input (?Input?) in the Downloading and sourcing section
- `setwd(indicator)` has disappeared from update_indicator_main.R, so prevents it from running!
- make sure `rm(list = ls())` in update_indicator_main.R is not commented out, so the automation starts from a clean slate and any existing variables don't interfere
- [x] csv output runs fine and seems correct
- overall run fails again due to Rmd checks when it comes to comparing old and new data (same issue and lines as before)

**Comment by ANikolova22** [comment]
FYI, the conflict markers are now present in update_indicator_main, so it will need to be cleaned up...

**Comment by MichaelGNairn** [comment]
> FYI, the conflict markers are now present in update_indicator_main, so it will need to be cleaned up... Basically, remove lines 14 and then 16 to 19 and should be fine

conflict resolved. 

Still checks file issue to resolve, but thought best to resolve conflict first

**Comment by ANikolova22** [comment]
Sadly, same thing is happening for me as before :( csv output is fine but Rmd is failing due to NAs in the new dataset - it happens after the two tables (old and new) and put together I believe. Here is a copy of the exact errors (warning messages can be ignored):

Quitting from lines 76-99 (3-5-1_checks.Rmd) 
Error: Problem with `mutate()` column `new`.
i `new = as.numeric(new)`.
x 'list' object cannot be coerced to type 'double'

Warning messages:
1: package ‘tidyr’ was built under R version 4.0.4 
2: package ‘dplyr’ was built under R version 4.0.5 
3: package ‘tibble’ was built under R version 4.0.5 
4: package ‘DT’ was built under R version 4.0.5 
5: Problem with `mutate()` column `Ethnicity_white`.
i `Ethnicity_white = as.integer(Ethnicity_white)`.
i NAs introduced by coercion 
6: Problem with `mutate()` column `Ethnicity_mixed`.
i `Ethnicity_mixed = as.integer(Ethnicity_mixed)`.
i NAs introduced by coercion 
7: Problem with `mutate()` column `Ethnicity_asian`.
i `Ethnicity_asian = as.integer(Ethnicity_asian)`.
i NAs introduced by coercion 
8: Problem with `mutate()` column `Ethnicity_black`.
i `Ethnicity_black = as.integer(Ethnicity_black)`.
i NAs introduced by coercion 
9: Problem with `mutate()` column `Ethnicity_other`.
i `Ethnicity_other = as.integer(Ethnicity_other)`.
i NAs introduced by coercion 
10: Problem with `mutate()` column `Total`.
i `Total = as.integer(Total)`.
i NAs introduced by coercion

**Review by ANikolova22 — APPROVED** [review]
Latest push solved the issues with the QA file, so now ready for approval.
**IMPORTANT**: once the live site is updated with the new data and disaggregations, the current QA file may not work properly, as it is currently accounting for the different data type between old and new

**Pull request merged**
