### PR TITLE
5 a 1 new

### PR DESCRIPTION
**Pull request by MichaelGNairn**
Updated 5-a-1 branch after I made a mess up of the original one!

### CODE REVIEW

**Comment by MichaelGNairn** [comment]
Initial problem noted by Ali.

Running by selecting source from "update_indicator_main.R" generates the .csv file, but then fails on the checks file 

_"Quitting from lines 22-42 (5-a-1_checks.Rmd) 
Error in eval(parse_only(code), envir = envir) : 
  object 'new_data' not found"_

However, then running the checks file by itself works, and after running line 58 of "compile_tables" 

_rmarkdown::render('5-a-1_checks.Rmd', 
                  output_file = paste0(output_folder, "/", qa_filename))_

produces the html file. 

@ANikolova22 @uzzelk  have you encountered this at all?

**Comment by MichaelGNairn** [comment]
@alicampbell2 you will have to run "git pull" on the 5-a-1_new branch in git bash. This means you will pull changes made by me this morning. Still same error you found though, see message above.

**Comment by ANikolova22** [comment]
I haven't encountered that specifically, but I've had many issues where things seem right, but still don't run - it's just a sneaky bug somewhere and you'd have to run everything manually line by line pretty much. In this case it's not finding the new_data variable, so may want to check if there is something being changed in the configurations between the different scripts. Search maybe for each instance you have that variable in any of the scripts (though I think it's just in the Rmd??) and check what is being assigned to it, if that makes sense. I'll have a look myself later today if I get a chance!

**Comment by MichaelGNairn** [comment]
> 

Sorted! Hot tip, don't call the variable "new_data" in the chunk of code before you actually create the variable "new_data"!

**Comment by MichaelGNairn** [comment]
@alicampbell2 you can have a go at this review now. Get in touch with me/Katie/Atanaska if any issues, and maybe have a look at reviews in closed pull requests https://github.com/ONSdigital/sdg_data_updates/pulls?q=is%3Apr+is%3Aclosed for inspiration.

**Review by alicampbell2 — COMMENTED** [review]
Initial review: all good, just a couple of formatting things [QA_5-a-1.Rmd.txt](https://github.com/ONSdigital/sdg_data_updates/files/10511881/QA_5-a-1.Rmd.txt)

**Comment by MichaelGNairn** [comment]
Removed repetition of text in README. 

Not applicable to have example input and output for a API (type_4) data type such as NOMIS. In effect there isn't an "input file". @ANikolova22, would this be correct? 

Have named the checks file as "DATE_5-a-1_checks.html". Agree this could cause confusion. 

"Maybe a quick line on the expected magnitude of the difference between the new and old data set." Have added something here. As you say, the differences should be small. However, for future updates (from the same, new source) there hopfeully shouldn't be any differences!

Have updated top of compile tables to reflect 5-a-1 instead of 3-c-1. 

Yes. new data source raises an issue here. My proposal is spot checks comparing the csv output file to the data directly on NOMIS website?

**Comment by ANikolova22** [comment]
Agree that automations exclusively pulling stuff from NOMIS or some other API don't need an Input folder. The input is automatically sorted out, so the user doesn't need to do anything

**Comment by MichaelGNairn** [comment]
> Removed repetition of text in README.
> 
> Not applicable to have example input and output for a API (type_4) data type such as NOMIS. In effect there isn't an "input file". @ANikolova22, would this be correct?
> 
> Have named the checks file as "DATE_5-a-1_checks.html". Agree this could cause confusion.
> 
> "Maybe a quick line on the expected magnitude of the difference between the new and old data set." Have added something here. As you say, the differences should be small. However, for future updates (from the same, new source) there hopfeully shouldn't be any differences!
> 
> Have updated top of compile tables to reflect 5-a-1 instead of 3-c-1.
> 
> Yes. new data source raises an issue here. My proposal is spot checks comparing the csv output file to the data directly on NOMIS website?

@alicampbell2 spot checks comparing the csv output file to the data directly on NOMIS website is the way to go.

**Comment by MichaelGNairn** [comment]
@alicampbell2 could you have a re-check of this please? Then approve the review/request further changes?

**Review by alicampbell2 — APPROVED** [review]
#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [x] **I recommend merging this request.**

**Review by alicampbell2 — APPROVED** [review]

**Pull request merged**
