### PR TITLE
ODA bug fixes

### PR DESCRIPTION
**Pull request by ANikolova22**
Fix of some ongoing bugs with the ODA code, and improving the code for 7.a.1 and 4.b.1, and 17-19-1. Summary of edits on this branch:

- The QA file should now be successfully generated as intended - only displaying information for the selected indicators in the config. There was a problem before where as part of the intro text the QA was looking for gni_api object regardless of which indicator was being updated. 
-  There were irrelevant warning messages printed before, which should only be reserved for indicators 1-a-1 and 15-b-1 under special circumstances. Those are fixed now with extra conditional statements.
- Added some more information in README and trimmed away some bits which were no longer true.
-  Edited the `example_config `to demonstrate how to automate a single indicator 
-  Added more CRS codes to 7.a.1 after topic expert noted that some data may be missing based on the UN metadata
-  Shuffled the column order of 4.b.1 to make consistent with other ODA
-  Changed the sentence case for 4.b.1 disaggregations after latest QA comments
- For 17-19-1 changed the units to USD (not constant) because this is what the UN metadata requires. Had some issues with working out the code, so did it in a clumsy way by copying some of the ODA functions in the main code, but it works fine

15-a-1/15-b-1 yields weird results for the non-ODA part (biodiversity) and needs to be investigated, but will do that in a separate pull request. From a quick look it seems like it's the OECD data that has been revised and is now mainly 0s, so not actually a problem with the code itself. 

**To whoever is reviewing this pull request** - try to run versions of single and multiple indicator updates and check if you get any errors. Also do run 15-a-1 to double check if you also get weird outputs for it. And as usual, read through the README in case it doesn't make sense as I did a few patchy edits there.

### CODE REVIEW

**Comment by ANikolova22** [comment]
Closing as more changes are required. Will re-open once those are integrated

**Comment by ANikolova22** [comment]
Added a few more edits (description updated), so now ready for review - shouldn't take long as not a lot of the original code has bee changed (see summary above)

**Comment by MichaelGNairn** [comment]
Have picked up and will hopefully get done tomorrow.

**Comment by ANikolova22** [comment]
Thanks Michael - no rush on this one!

**Comment by ANikolova22** [comment]
FYI, I just did an extra change to the code for 17-19-1, so worth updating the branch is it's already pulled locally. This will not make any difference to the edits so far as it's contained within the 17-19-1 script (and the QA bits for it)

**Review by abhsheksingh — APPROVED** [review]
Minor change to the main script, seems fine

**Review by MichaelGNairn — CHANGES_REQUESTED** [review]
See attached review. Also, 
In config file:
deflators_filename <- "Deflators-base-2021.xlsx" instead of 2020. 
[2023-04-19_update_17-19-1.csv](https://github.com/ONSdigital/sdg_da
[Michael Nairn - Code review for ODA bug fixes.docx](https://github.com/ONSdigital/sdg_data_updates/files/11271193/Michael.Nairn.-.Code.review.for.ODA.bug.fixes.docx)
ta_updates/files/11271189/2023-04-19_update_17-19-1.csv)
file:///Z:/Data%20Collection%20and%20Reporting/Jemalex/sdg_data_updates/ODA/Output/2023-04-19_oda_update_checks.html

**Comment by MichaelGNairn** [comment]
Readme changes good. 

Still need to change the deflators filename to 2021 in "example_config"? 
And the constant USD issue in 17-19-1

**Comment by ANikolova22** [comment]
Thanks @MichaelGNairn ! I have edited the readme now and also added clarification in the example config - edited out the year of the deflators and put YYYY instead, as people will have to use the latest file and rename accordingly. The readme also explains that.

The edits of 17.19.1 should produce USD (thousands) value, without using the deflators. I also added a "Units multiplier" column as it was missing before. I removed the $ and £ signs from the Unit label because that was causing havoc when I was creating the feature branch (in fact, looking at SDMX standards they should not be there at all, it should just say USD or GBP, but I kept the "thousands" as a reminder for the user, as this indicator is not reported through SDMX anyway so we have flexibility". 

If you pull the changes onto your local branch, the results should be identical to what I currently have on the feature branch for review. Hope you won't have any issues, runs smoothly for me!

**Review by MichaelGNairn — APPROVED** [review]

**Comment by MichaelGNairn** [comment]
pulled to local branch and works perfectly now, same as on FB.

**Pull request merged**
