### PR TITLE
3-2-2 and SDGupdater

### PR DESCRIPTION
**Pull request by EmmaWoodONS**
This code should be in a working state though unit tests for SDGupdater are not yet complete

### CODE REVIEW

**Comment by alexander-newton** [comment]
##  Code review

As per review session on 2021-04-19; with @varunjakki, @morrid9, @ANikolova22, @jaetowers, @EmmaWoodONS 

#### Documentation

Any new code includes all the following forms of documentation:

- [x] **Function Documentation** as docstrings within the function definition.
    - For the main functions documented well
    - Understood what most of each function did
- [x] **Examples** demonstrating major functionality, which runs successfully locally.
    - Integration test might be useful showing output?

#### Functionality

- [x] **Installation**: Installation or build of the code succeeds.
    - On multiple computers; although on R 4.0.0+ the `library(SDGupdater)` call didn't work on Alex's computer
- [ ] **Functionality**: Any functional claims of new code have been confirmed.

    - @varunjakki changed to input folder
        - created empty output folder to get output
        - [ ] if there is something already in the output folder then it won't work, needs to overwrite, write with timestamp in filename?
        - `?function_name` a lot had description and usage documented twice
        - csv output - in the value column there were blanks -- ideally no blanks in indicator folder
    - @morrid9 Wales put in region?
    - 
- [ ] **Automated tests**: Unit tests cover essential functions for a reasonable range
  of inputs and conditions. All tests pass on your local machine.
    - good start and just go out across 
- [ ] **Packaging guidelines**: New code conforms to the project contribution
  guidelines.
     - write `CONTRIBUTING.MD` guidance for people contributing to the code

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

Estimated time spent reviewing: #

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- general architecture

- [ ] config.yml
- https://github.com/best-practice-and-impact/CARS-2 for example
- .Rproj file move to TL
- avoid `setwd`
- avoid `source`
- avoid `library`, use namespace operator 
- 

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)

- [ ] Wales in region


- @ANikolova22 
        - folder with example data is named `example_data` in the branch but some of the functions expected it to be named `input` but then it wouldn't work, some of the functions expected `input`, some expected `example_data`
        - [ ] needs a tweak in the config file
        - is the `output` folder expected to exist already?
        - [ ] currently hardcoded to be on the H: drive, not explicitly mentioned in the documentation
        - [ ] bug where no longer displaying options
        - [ ] instructions for users if they want to escape user input

- [ ] @morrid9 retained M or F, should be male or female
- [ ] @varunjakki sometimes two geocodes come up in one cell; e.g. E&W2017 some cells have two geocodes, even though they are the same region

- alternative methods (could it be written more efficiently or with more clarity?)

- `message` rather than `cat` 
- 

- documentation improvements (does the documentation reflect how the code actually works?)

- [ ] how to use config for users
- [ ] how to install - installation instructions in README
- [ ] dependencies 
- [ ] inputs might need to be clearer specified
- [ ] 

- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)


- code style improvements (could the code be written more clearly?)



Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

**Comment by ANikolova22** [comment]
I edited Alex's main comment so all info is contained in the same place - just added a few more details from my notes regarding the input folder and a minor additional suggestion for the documentation check lists. Also, forgot to explicitly state this at the meeting, but it was very useful (I learnt a lot), and also - great job @EmmaWoodONS for putting all this together!

**Comment by EmmaWoodONS** [comment]
All fixes made to 3-2-2, still need to address some issues in SDGupdater, and finish writing unit tests

**Comment by EmmaWoodONS** [comment]
Finished edits to SDGupdater. Had some issues with packrat, so would be good to see if this works on someone else's computer, before signing off and pushing to main. @ANikolova22 @morrid9 @varunjakki any volunteers? If we could share screen to do it, I would find that useful.

**Comment by morrid9** [comment]
I'm happy to test this @EmmaWoodONS

**Pull request closed without merging**
