### PR TITLE
8 6 1

### PR DESCRIPTION
**Pull request by abhsheksingh**

### CODE REVIEW

**Comment by abhsheksingh** [comment]
All QA comment addressed 👍

**Comment by uzzelk** [comment]
Hi @abhsheksingh 

Thanks for making the changes. 

Just a couple more needed:

- The README.md file needs updating (as it still says to copy and paste the tables into the excel file)

- You've still got 2 separate scripts doing the update (update_8.6.1.R and function.R) and you now call them both in compile_tables.R - however, both of them output a dataframe called csv_output so the second script is overwriting things from the first script (I think...). I recommend **combining the code from update_8.6.1.R and function.R into one script** (called update_8.6.1.R) and only calling this script in compile_tables.R - it will make the code much simpler, and there doesn't seem to be a need for the separate scripts...

Otherwise, the 2 outputs are saved as expected and the html checks file looks much clearer now the dates have been turned 😄

**Comment by abhsheksingh** [comment]
> Hi @abhsheksingh
> 
> Thanks for making the changes.
> 
> Just a couple more needed:
> 
> * The README.md file needs updating (as it still says to copy and paste the tables into the excel file)
> * You've still got 2 separate scripts doing the update (update_8.6.1.R and function.R) and you now call them both in compile_tables.R - however, both of them output a dataframe called csv_output so the second script is overwriting things from the first script (I think...). I recommend **combining the code from update_8.6.1.R and function.R into one script** (called update_8.6.1.R) and only calling this script in compile_tables.R - it will make the code much simpler, and there doesn't seem to be a need for the separate scripts...
> 
> Otherwise, the 2 outputs are saved as expected and the html checks file looks much clearer now the dates have been turned 😄




Thanks Katie for the review & comments, I made the changes.

**Review by uzzelk — APPROVED** [review]
Thanks for making the changes - code runs fine for me now so happy to approve. Final, fonal change to README needed though...

Line 14 - delete the following: ", this file is present in the Example_Input folder." (Because the person running the update would need to download the newest data, not copy and paste the old file from example_input, so this sentence in not needed.

**Comment by abhsheksingh** [comment]
Sure Thanks Katie,  I will change the Readme file and then merge it to main.

**Pull request merged**
